### ISSUE TITLE
[Meta] things to resolve before 1.0.0

### ISSUE THREAD

**Issue by sstok** [rollerworks/search#36]
Because the RollerworksSearch system is decoupled into multiple packages (for good reason) I'm creating this this meta issue to keep track of things that need to be before the big 1.0.0 release later this year. First there will be a release candidate to straiten out some minor bugs that we may find.

## All

* [x] Check documentation (all packages, add package to sublist when reviewing or done)
    * [x] RollerworksSearch (#44)
    * [x] metadata (missing documentation)
    * [ ] symfony-validator (documentation not sufficient)
    * [x] doctrine-dbal
    * [x] doctrine-orm
* [x] Ensure there's a beta tag with the latest changes (all packages, when planned work is done)
  * [x] metadata
  * [x] symfony-di
  * [x] symfony-validator
  * [x] doctrine-dbal
  * [x] doctrine-orm
  * [x] doctrine-dbal-bundle
  * [x] doctrine-orm-bundle

* [x] Make sure the installation instructions are uniform for all packages
  * [x] metadata
  * [x] symfony-di
  * [ ] symfony-validator

## RollerworksSearch component

* [x] Update README.md (do this right after opening "this" issue)
* [x] [Move Symfony validator to its own package](https://github.com/rollerworks/RollerworksSearch/issues/35)
* [x]  Replace OptionsResolverInterface with OptionsResolver (#48)
* [x] [[Input] make QueryException easier to use](https://github.com/rollerworks/RollerworksSearch/issues/10)

## RollerworksSearchBundle

* [x] [Resolve hard dependency on the rollerworks/search-jms-metadata package](https://github.com/rollerworks/RollerworksSearchBundle/issues/9)
* [x] [Search processor](https://github.com/rollerworks/RollerworksSearchBundle/pull/8)
* [x] Add a configuration bundle for Doctrine DBAL (ORM is already done) (#65)

**Comment by sstok** [comment]
Done.

**Comment by sstok** [comment]
The documentation for the Symfony validator needs to be updated, this is really hard to read.

**Comment by cordoval** [comment]
hmm not sure i follow or why you reopened this

**Comment by sstok** [comment]
* [x] Ensure there's a 1.0.0 tag with the latest changes
  * [x] symfony-di
  * [ ] symfony-bundle
  * [x] symfony-validator
  * [ ] doctrine-dbal
  * [ ] doctrine-orm
  * [ ] doctrine-dbal-bundle
  * [ ] doctrine-orm-bundle

**Comment by sstok** [comment]
Only the bundles need to be tagged, but the "core" bundle needs to be updated to use the Rollerworks Metadata component (and not the JMS metadata library).
